import {
  Award,
  BadgeCheck,
  Banknote,
  Box,
  CheckCircle2,
  Clock,
  CreditCard,
  Flame,
  Gift,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  Leaf,
  Lock,
  MapPin,
  MessageCircle,
  Package,
  PackageCheck,
  Percent,
  Phone,
  RefreshCw,
  Ruler,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  ThumbsUp,
  Timer,
  Trophy,
  Truck,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * The icons a landing-page block may reference by name. Kept as an explicit
 * registry rather than a dynamic import so an unknown name from hand-edited
 * jsonb falls back instead of crashing the renderer.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  ShieldCheck,
  Truck,
  BadgeCheck,
  CheckCircle2,
  PackageCheck,
  Star,
  Heart,
  HeartHandshake,
  Zap,
  Flame,
  Sparkles,
  Package,
  Box,
  Gift,
  Clock,
  Timer,
  Phone,
  Headphones,
  MessageCircle,
  CreditCard,
  Banknote,
  Wallet,
  Percent,
  RefreshCw,
  Award,
  Trophy,
  ThumbsUp,
  Smile,
  Users,
  Handshake,
  MapPin,
  Lock,
  Leaf,
  Ruler,
  Wrench,
};

export function resolveIcon(name: string | undefined | null): LucideIcon {
  return (name && ICON_REGISTRY[name]) || BadgeCheck;
}
